### ISSUE TITLE
What does the AES algorithm do?

### ISSUE THREAD

**Issue by relaxbao** [multiparty/jigg#6]
hi，

We have a variety  of  circuits available  under `circuits/bristol` ,  What does AES-128.txt do?  there are two inputs here, are they key and message for AES encryption?  there is  1 output，it's length is 128bit, what is the content of this output?

look forward for your reply  ,thanks

**Comment by wyatt-howe** [comment]
Hello,

JIGG mainly reads circuits in Bristol Fashion described [here](https://homes.esat.kuleuven.be/~nsmart/MPC/).  Although we have created a few circuits by hand and from [macro](https://github.com/multiparty/jigg#circuit-assembler) circuits, most of the circuits in `circuits/bristol` were taken from the Bristol Fashion page.

We are hoping to document each circuit's descriptions in the future.  For aes_128.txt, it takes a 128-bit key and a 128-bit message and returns a 128-bit ciphertext with bits in little-endian representation which is the opposite of it's inputs.  For this reason we have an alternate AES-128 circuit called [aes-128-reverse.txt](https://raw.githubusercontent.com/multiparty/jigg/master/circuits/bristol/aes-128-reverse.txt) which should return ciphertext values as expected.  Our tests use [these](https://github.com/multiparty/jigg/blob/916ce61210cc41588663592ba5f63cf6a54871ad/test/aes-128-reverse.js#L7-L26) test vectors for aes-128-reverse.txt from [here](https://opensource.apple.com/source/KerberosLibraries/KerberosLibraries-81.46.4/KerberosFramework/Kerberos5/Sources/lib/crypto/aes/test/ecb_tbl.txt.auto.html).

**Comment by relaxbao** [comment]
> Hello,
> 
> JIGG mainly reads circuits in Bristol Fashion described [here](https://homes.esat.kuleuven.be/~nsmart/MPC/). Although we have created a few circuits by hand and from [macro](https://github.com/multiparty/jigg#circuit-assembler) circuits, most of the circuits in `circuits/bristol` were taken from the Bristol Fashion page.
> 
> We are hoping to document each circuit's descriptions in the future. For aes_128.txt, it takes a 128-bit key and a 128-bit message and returns a 128-bit ciphertext with bits in little-endian representation which is the opposite of it's inputs. For this reason we have an alternate AES-128 circuit called [aes-128-reverse.txt](https://raw.githubusercontent.com/multiparty/jigg/master/circuits/bristol/aes-128-reverse.txt) which should return ciphertext values as expected. Our tests use [these](https://github.com/multiparty/jigg/blob/916ce61210cc41588663592ba5f63cf6a54871ad/test/aes-128-reverse.js#L7-L26) test vectors for aes-128-reverse.txt from [here](https://opensource.apple.com/source/KerberosLibraries/KerberosLibraries-81.46.4/KerberosFramework/Kerberos5/Sources/lib/crypto/aes/test/ecb_tbl.txt.auto.html).

Thank you so  much for your reply ~ 
since  [here](https://homes.esat.kuleuven.be/~nsmart/MPC/) didn't mention how does aes-128.txt work .  i must ask one more question :  AES can be used to encrypt and decrypt,  I can encrypt with aes-128.txt,  how can I decrypt the output?

**Comment by wyatt-howe** [comment]
The `aes-128.txt` circuit works by the garbler party inputting a 128-bit key, and the evaluator party inputting a 128-bit message block.  The result is one 128-bit AES ciphertext block.

This is only for enciphering (aka one block encryption of ECB mode).  If you are hoping to decrypt ciphertexts _privately_ within JIGG (instead of publicly), you will have to use a mode of operation such as [counter mode](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Counter_(CTR)).  The `aes-128.txt` circuit only enciphers one 128-bit block.

I see how calling using the term 'reverse' in the circuit's name is misleading.  We do not have a fast AES inverse circuit (to decipher) that matches `aes-128.txt`.  _However_, we do an experimental one.

Yesterday my colleague synthesized two new circuits for AES encryption and one for AES decryption: `aes-128-ecb-encrypt.txt` , `aes-128-ecb-decrypt.txt`.  I have not had time to test them beyond a few times, and would not recommend using a circuit that large yet.  (If you need decryption use CTR mode, or possibly write a 128-bit XOR for CBC mode.)

**Comment by relaxbao** [comment]
> The `aes-128.txt` circuit works by the garbler party inputting a 128-bit key, and the evaluator party inputting a 128-bit message block. The result is one 128-bit AES ciphertext block.
> 
> This is only for enciphering (aka one block encryption of ECB mode). If you are hoping to decrypt ciphertexts _privately_ within JIGG (instead of publicly), you will have to use a mode of operation such as [counter mode](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Counter_(CTR)). The `aes-128.txt` circuit only enciphers one 128-bit block.
> 
> I see how calling using the term 'reverse' in the circuit's name is misleading. We do not have a fast AES inverse circuit (to decipher) that matches `aes-128.txt`. _However_, we do an experimental one.
> 
> Yesterday my colleague synthesized two new circuits for AES encryption and one for AES decryption: `aes-128-ecb-encrypt.txt` , `aes-128-ecb-decrypt.txt`. I have not had time to test them beyond a few times, and would not recommend using a circuit that large yet. (If you need decryption use CTR mode, or possibly write a 128-bit XOR for CBC mode.)

ok, I see, thank you so much for your reply ~
